/**
 * Phase 6A: Milestone AI Foundation Types
 * This file contains interfaces and configuration types for the server-side AI layer.
 */

/**
 * Structure of a suggested milestone generated by the breakdown AI.
 */
export interface MilestoneSuggestion {
  title: string;
  description: string;
  suggested_deadline: string; // ISO date string (YYYY-MM-DD) or offset descriptor
  suggested_payout: number;
}

/**
 * Structure of a status update draft generated by the update assist AI.
 */
export interface StatusUpdateDraft {
  title: string;
  message: string;
  progressSummary: string;
  blockers: string | null;
  nextSteps: string | null;
}

/**
 * Structure of a scope creep comparison report.
 */
export interface ScopeCreepAnalysis {
  isScopeCreep: boolean;
  confidence: number; // Value between 0.0 and 1.0
  classification: "WITHIN_SCOPE" | "POSSIBLE_SCOPE_CREEP" | "LIKELY_SCOPE_CREEP";
  explanation: string;
  matchedExistingScope: string | null;
  recommendedAction: string;
}

/**
 * Configuration options resolved for the current active provider.
 */
export interface AIProviderConfig {
  provider: "gemini" | "openai" | "mock";
  apiKey: string;
  model: string;
  timeoutMs: number;
}

/**
 * Metrics captured for tracking LLM requests and latencies.
 */
export interface AILogMetrics {
  feature: "milestone-breakdown" | "status-update" | "scope-creep";
  provider: "gemini" | "openai" | "mock";
  success: boolean;
  latencyMs: number;
  errorCategory?: "TIMEOUT" | "RATE_LIMIT" | "MALFORMED_JSON" | "API_ERROR" | "NETWORK_ERROR" | "CONFIG_ERROR" | null;
}
